# Generated by Django 4.2.4 on 2025-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_removal',
            field=models.BooleanField(default=False, help_text='Marcar si este servicio necesita una cita de seguimiento para retiro (ej. Suero).', verbose_name='Requiere Cita de Retiro'),
        ),
    ]
