# Generated by Django 4.2.4 on 2025-04-23 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0005_appointment_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='enfermero',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'enfermero'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Enfermero asignado'),
        ),
    ]
