# Generated by Django 4.2.4 on 2025-04-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_tipo_ubicacion_appointment_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mapa_ubicacion',
            field=models.URLField(blank=True, help_text='Enlace a Google Maps para la cita.', max_length=500, null=True, verbose_name='Ubicación en Google Maps'),
        ),
    ]
