# Generated by Django 4.2.4 on 2025-05-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_appointment_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Doctor'),
        ),
    ]
