# Generated by Django 4.2.4 on 2025-04-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_zona'),
        ('users', '0005_user_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zona',
        ),
        migrations.AddField(
            model_name='user',
            name='zonas',
            field=models.ManyToManyField(blank=True, related_name='enfermeros', to='core.zona', verbose_name='Zonas'),
        ),
    ]
